project:
  type: website
  output-dir: docs
 
website:
  title: "zool710-intro-sunyoung-park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



