---
title: "zool710-intro-sunyoung-park"
---

Aloha!

# About ME
My name is Sun, and I am a 2nd year Botany PhD student at the University of Hawai‘i at Mānoa. 

## Background & Research Interest

I graduated with a B.S. in Environmental Systems: Ecology, Behavior and Evolution at the University of California, San Diego, with a minor in Anthropological Archaeology in 2019. 

I am interested in studying pollination biology and reproductive systems of native and non-native plant species in Hawai‘i. Particularly, I'm looking at mechanisms of low seed set rates in a rare endangered endemic species, Dubautia herbstobatae, as well as a common non-native species, Spagneticola trilobata.

## Fun facts about myself

* I have lived in four different countries. 

* I had wanted to be a marine biologist up until my last year of undergraduate, and then I worked on a project studying terrestrial plants for my senior thesis, which completely changed my career path.

## ʻenaʻena (Pseudognaphalium sandwicensium var. molokaiense) 

This link shows pictures of my favorite endemic plant species, ʻenaʻena. It historically occurred on western Molokaʻi, west Maui, Lānaʻi, and Oʻahu, and currently occurs on Molokaʻi (four populations total fewer than 300 individuals) and the northwest coast of Maui (one population total ~20 individuals). 

* http://www.botany.hawaii.edu/faculty/carr/pseudognaphalium.htm



